### ISSUE TITLE
Update PyPI release

### ISSUE THREAD

**Issue by lordminx** [Chronister/ananas#15]
The ananas version currently in PyPI doesn't include the "async->run_async" fix  (b33bba8dbad1c196445b4f2db99da85b82744af0) yet, while the current version of Mastodon.py already does, resulting in errors like this:

> Traceback (most recent call last):
  File "/home/lordminx/.local/share/virtualenvs/glitch_art-cmsPNbAw/lib/python3.6/site-packages/ananas/run.py", line 44, in main
    .format(module, botclass, args.config, bot, args.interactive, args.verbose))
  File "<string>", line 1, in <module>
  File "/home/lordminx/.local/share/virtualenvs/glitch_art-cmsPNbAw/lib/python3.6/site-packages/ananas/ananas.py", line 269, in __init__
    self.startup()
  File "/home/lordminx/.local/share/virtualenvs/glitch_art-cmsPNbAw/lib/python3.6/site-packages/ananas/ananas.py", line 332, in startup
    self.stream = self.mastodon.stream_user(self, async=True)
TypeError: stream_user() got an unexpected keyword argument 'async'

**Comment by chr-1x** [comment]
I think this should be fixed, thanks for the notice
